name: direct_task_web
description: "Direct Task App - Flutter Web Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # =========================
  # UI & RESPONSIVENESS
  # =========================
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1

  # =========================
  # STATE & NAVIGATION
  # =========================
  get: ^4.6.6

  # =========================
  # UI HELPERS
  # =========================
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1

  # =========================
  # UTILITIES
  # =========================
  intl: ^0.19.0

  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/